Add test to replicate duplicate port hints issue
tscircuit/builder pull request #97
Opened 2024-08-08 18:13 UTC by abhijitxy

- [x] Added a test to replicate the issue of duplicate port hints by creating a `bug` with `footprint="soic8"`.

2024-08-08 18:14 UTC, abhijitxy commented
@seveibar review it

2024-08-09 16:40 UTC, seveibar requested changes
Oh i would make this test fail (duplicates are a bug) then fix the duplicate port hints issue. Wasnt sure if you were waiting on a review, if we merged as is we would be protecting the buggy behavior

2024-08-09 16:57 UTC, abhijitxy commented
Yeah @seveibar, I know. I'll fix the bug. Thanks for the catch!

2024-08-11 17:17 UTC, seveibar requested changes

2024-08-11 17:17 UTC, seveibar commented on tests/bug-builder/duplicate-port-hints.test.tsx
> +  console.log("All source ports:", JSON.stringify(sourcePorts, null, 2))
```suggestion
```

2024-08-11 17:17 UTC, seveibar commented on tests/bug-builder/duplicate-port-hints.test.tsx
> +    console.log(`Port ${port.name} hints:`, port.port_hints)
```suggestion
```

2024-08-11 17:18 UTC, seveibar commented
Looks good, good fix. Normally i approve with suggestions but since this is an early pr i requested changes

2024-08-11 17:51 UTC, seveibar approved these changes
Lets make sure the tests pass but then looks good. I think they should autorun next time

2024-08-11 17:51 UTC, seveibar commented
@abhijitxy i think you're failing format, formatbot usually fixes this but cant on forks iirc, try running nom run format

2024-08-11 18:30 UTC, merged